#!/usr/bin/python3

import os
import subprocess

path = os.environ.get("PATH_INFO")
p = subprocess.Popen(
    ["python3", path],
    stdin=subprocess.PIPE,
    stdout=subprocess.PIPE)
output, _ = p.communicate(input=open(0, "rb").read())
print(output.decode(), end="")
